import styles from "../styles/Home.module.css";
import Head from "next/head";
// import ManualHeadr from "./../components/ManualHeader";
import Header from "../components/Header";
import LotteryEntrance from "../components/LotteryEntrance";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Lottery App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <LotteryEntrance />
      {/* <ManualHeadr /> */}
    </div>
  );
}
